### ISSUE TITLE
change of name broke downstream

### ISSUE THREAD

**Issue by joshgav** [Azure/azure-pipeline-go#7]
I think 6ef5c39261c7d60c7e2327632e968e4a241d4e2c might've broken Azure/azure-storage-blob-go.

output of `go get -u github.com/Azure/azure-storage-blob-go/2016-05-31/azblob`:

```
# github.com/Azure/azure-storage-blob-go/2016-05-31/azblob
../../Azure/azure-storage-blob-go/2016-05-31/azblob/credential_anonymous.go:27:78: undefined: pipeline.Configuration
../../Azure/azure-storage-blob-go/2016-05-31/azblob/credential_shared_key.go:42:65: undefined: pipeline.Configuration
../../Azure/azure-storage-blob-go/2016-05-31/azblob/credential_shared_key.go:53:11: undefined: pipeline.Configuration
```

I discovered this while running tests in the samples repo :)

**Comment by JeffreyRichter** [comment]
Yes, I know about this. I'll fix it this weekend.

-- Jeffrey Richter (watch Architecting Distributed Cloud Apps<https://aka.ms/RichterCloudApps> on YouTube<https://aka.ms/RichterCloudApps> or edX<https://aka.ms/edx-devops200_9x-about>)
________________________________

**Comment by JeffreyRichter** [comment]
I just accepted the PR that fixes this issue.
