### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by ehotinger** [Azure/azure-pipeline-go#9]
What's going on with the versioning for the releases in this repo - it went from 0.1.0 -> 1.1.3, back down to 0.1.3 -> 0.1.4. Surely all releases should have a major rev of 1 at this point...? It seems like this just causes lots of weird issues since some tools can't tell whether or not it should actually update based off the rev number, and you instead have to just fetch the latest @ master.

**Comment by JeffreyRichter** [comment]
That was a release versioning bug. 0.1.4 is the latest.
